POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQ0NTg1NjUsInN1YiI6IjcyY2I5NWZhLTE0MWQtNDhmZi05NzQxLWZmM2MyZmZhOTBhYiJ9.J_Zie6H6rzbdZSH4jW2fnDYPx-VmhmQy0CknLp_DCQg

{
  "name": "Teste product using chi",
  "price": 100
}

###

GET http://localhost:8080/products HTTP/1.1



###

GET http://localhost:8080/products/3dba6b8a-e902-4f81-8b6f-2bd64e0bb33b HTTP/1.1

###
PUT http://localhost:8080/products/3dba6b8a-e902-4f81-8b6f-2bd64e0bb33b HTTP/1.1
Content-Type: application/json

{
  "name": "Teste update",
  "price": 100
}



###

DELETE  http://localhost:8080/products/3dba6b8a-e902-4f81-8b6f-2bd64e0bb33b HTTP/1.1

